version: '2'

services:
  database:
    environment:
      - POSTGRES_USER=navitia
      - POSTGRES_PASSWORD=navitia
      - POSTGRES_DB=jormungandr
    image: mdillon/postgis:9.1

  rabbitmq:
    image: rabbitmq:management

  kraken_default:
    build: ./kraken
    volumes:
      - ./data/default:/srv/data
    volumes_from:
      - tyr_worker:ro
    links:
      - rabbitmq

  jormungandr:
    build: ./jormungandr
    links:
      - kraken_default
      - rabbitmq
      - database

  tyr_worker:
    build: ./tyr_worker
    links:
      - database
      - rabbitmq
  
  tyr_beat:
    build: ./tyr_beat
    links:
      - database
      - rabbitmq

  tyr_web:
    build: ./tyr_web
    links:
      - database

