version: '2'

services:
  instances_configurator:
    build: ./instances_configurator
    volumes_from:
      - tyr_beat
      - tyr_worker
      - jormungandr
      - kraken-default

  database:
    environment:
      - POSTGRES_USER=navitia
      - POSTGRES_PASSWORD=navitia
      - POSTGRES_DB=jormungandr
    image: mdillon/postgis:9.1

  rabbitmq:
    image: rabbitmq:management

  redis:
    image: redis:3-alpine

  kraken-default:
    image: kraken
    command: sh -c "while [ ! -f /srv/kraken/default.ini ]; do echo "waiting" && sleep 1; done && ./kraken /srv/kraken/default.ini"
    volumes:
      - kraken_instance_conf:/srv/kraken

    #build: ./kraken
    volumes_from:
      - tyr_beat:ro
    expose:
      - "30000"

  jormungandr:
    #build: ./jormungandr
    image: jormungandr
    volumes:
      - jormungandr_instance_conf:/etc/jormungandr.d
    ports:
      - "9191:80"

  tyr_worker:
    #build: ./tyr_worker
    image: tyr
    volumes:
      # TODO this is not necessary, it's just by convenience, remove this to import it directly in instances_configurator
      - ed_migration:/usr/share/navitia/ed
    volumes_from:
      - tyr_beat

  tyr_beat:
    build: ./tyr_beat
    volumes:
      - tyr_data:/srv/ed
      - tyr_instance_conf:/etc/tyr.d

  tyr_web:
    build: ./tyr_web
    volumes_from:
      - tyr_beat
    ports:
      - '9898:80'

volumes:
  tyr_data:
  tyr_instance_conf:
  jormungandr_instance_conf:
  kraken_instance_conf:
  ed_migration:
